"""Second migration

Revision ID: 21a71c41a07b
Revises: ab848cbca204
Create Date: 2024-10-02 11:00:19.398152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a71c41a07b'
down_revision = 'ab848cbca204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
